### ISSUE TITLE
É necessário um novo repositório?

### ISSUE THREAD

**Issue by Anderson-Juhasc** [btcbrdev/fullnodetutorial#1]
@paladini esse artigo não pode fazer parte do repo AprendaBitcoin?

**Comment by Anderson-Juhasc** [comment]
Ou criar um repo para focamos em criação de tutoriais?

**Comment by felipelalli** [comment]
Pode ser uma página wiki do AprendaBitcoin. "Como configurar um nó completo (full node)"

**Comment by Anderson-Juhasc** [comment]
Temos que fazer um site para o AprendaBitcoin, @paladini tu pode montar algo com Jekyll pois tem facilidade com ruby ;).

**Comment by paladini** [comment]
Puts, foi mal galera, só vi essa Issue agora. 

Enfim, não acham que podemos deixar aqui? A ideia era disponibilizar esse tuto em inglês também e criar um site para colocar os artigos para vários sistemas operacionais. Acham que daria muito trabalho e o impacto seria baixo? 

Se o custo/benefício não for bom, criamos apenas uns tutos no AprendaBitcoin mesmo. Vale constar que tem gente que estuda que nem cavalo, está na Fundação e deve ter uns 3.000 projetos em dívida com o @Anderson-Juhasc , então o tempo pode ser um recurso bem escasso (o que é ruim para esse projeto caso o custo/benefício dele não seja bom).

**Comment by Anderson-Juhasc** [comment]
@paladini você não precisa fazer o site mais bonito do mundo e outra jekyll fornece facilidade de tradução, ele é usado nas trades da blinktrade para esse fim.

Acho que o tutorial deve acontecer dentro do AprendaBitcoin.

**Comment by paladini** [comment]
Vou colocar o tuto lá então, deixa que eu encerro esse repo.
